# Generated by Django 3.0.5 on 2024-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_myformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toux', models.CharField(max_length=100)),
                ('douleur_musculaire', models.CharField(max_length=30)),
                ('appetit', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='MyFormData',
        ),
    ]
